# Generated by Django 4.1.1 on 2022-09-20 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nick_name',
            new_name='sort_name',
        ),
    ]
