# Generated by Django 4.1.1 on 2022-09-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_extraadd_dropyou'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropyou',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
