# Generated by Django 4.1.1 on 2022-09-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropyou',
            name='text',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to=''),
        ),
    ]
