# Generated by Django 4.1.1 on 2022-09-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_dropyou_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropyou',
            name='text',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
