# Generated by Django 4.1.1 on 2022-09-25 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_dropyou_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropyou',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userprofile'),
        ),
    ]
